apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${K8S_NAME}
  labels:
    app: ${K8S_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ${K8S_STORAGE_CLASS}
  volumeMode: Filesystem

